# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/d2att/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/samsung/d2att/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so \
	vendor/samsung/d2att/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
        vendor/samsung/d2att/proprietary/lib/libv8.so:obj/lib/libv8.so 

PRODUCT_COPY_FILES += \
        vendor/samsung/d2att/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
        vendor/samsung/d2att/proprietary/bin/btnvtool:system/bin/btnvtool \
        vendor/samsung/d2att/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
        vendor/samsung/d2att/proprietary/bin/immvibed:system/bin/immvibed \
        vendor/samsung/d2att/proprietary/bin/mpdecision:system/bin/mpdecision \
        vendor/samsung/d2att/proprietary/bin/netmgrd:system/bin/netmgrd \
        vendor/samsung/d2att/proprietary/bin/port-bridge:system/bin/port-bridge \
        vendor/samsung/d2att/proprietary/bin/qmiproxy:system/bin/qmiproxy \
        vendor/samsung/d2att/proprietary/bin/qmuxd:system/bin/qmuxd \
        vendor/samsung/d2att/proprietary/bin/sec-ril:system/bin/sec-ril \
        vendor/samsung/d2att/proprietary/bin/rmt_storage:system/bin/rmt_storage \
        vendor/samsung/d2att/proprietary/bin/usbhub:system/bin/usbhub \
        vendor/samsung/d2att/proprietary/bin/usbhub_init:system/bin/usbhub_init \
        vendor/samsung/d2att/proprietary/bin/thermald:system/bin/thermald \
        vendor/samsung/d2att/proprietary/etc/thermald.conf:system/etc/thermald.conf \
        vendor/samsung/d2att/proprietary/etc/thermald.conf_F:system/etc/thermald.conf_F \
        vendor/samsung/d2att/proprietary/etc/thermald.conf_N:system/etc/thermald.conf_N \
        vendor/samsung/d2att/proprietary/etc/thermald.conf_S:system/etc/thermald.conf_S \
        vendor/samsung/d2att/proprietary/bin/bcm4334.hcd:system/bin/bcm4334.hcd \
        vendor/samsung/d2att/proprietary/bin/bcm4334_murata.hcd:system/bin/bcm4334_murata.hcd \
        vendor/samsung/d2att/proprietary/bin/bcm4334_semco.hcd:system/bin/bcm4334_semco.hcd \
        vendor/samsung/d2att/proprietary/lib/hw/alsa.msm8960.so:system/lib/hw/alsa.msm8960.so \
        vendor/samsung/d2att/proprietary/lib/hw/audio_policy.msm8960.so:system/lib/hw/audio_policy.msm8960.so \
        vendor/samsung/d2att/proprietary/lib/hw/audio.primary.msm8960.so:system/lib/hw/audio.primary.msm8960.so \
        vendor/samsung/d2att/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
        vendor/samsung/d2att/proprietary/lib/libalsa-intf.so:system/lib/libalsa-intf.so \
        vendor/samsung/d2att/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
        vendor/samsung/d2att/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
        vendor/samsung/d2att/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
        vendor/samsung/d2att/proprietary/lib/libaudiopolicy_sec.so:system/lib/libaudiopolicy_sec.so \
        vendor/samsung/d2att/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
        vendor/samsung/d2att/proprietary/lib/lib_SamsungRec_V01005.so:system/lib/lib_SamsungRec_V01005.so \
        vendor/samsung/d2att/proprietary/lib/libcontrolcsc.so:system/lib/libcontrolcsc.so \
        vendor/samsung/d2att/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
        vendor/samsung/d2att/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
        vendor/samsung/d2att/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
        vendor/samsung/d2att/proprietary/lib/libv8.so:system/lib/libv8.so \
        vendor/samsung/d2att/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
        vendor/samsung/d2att/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
        vendor/samsung/d2att/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
        vendor/samsung/d2att/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
        vendor/samsung/d2att/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
        vendor/samsung/d2att/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
        vendor/samsung/d2att/proprietary/lib/libgsl.so:system/lib/libgsl.so \
        vendor/samsung/d2att/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
        vendor/samsung/d2att/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
        vendor/samsung/d2att/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
        vendor/samsung/d2att/proprietary/bin/netmgrd:system/bin/netmgrd \
        vendor/samsung/d2att/proprietary/bin/sec-ril:system/bin/sec-ril \
        vendor/samsung/d2att/proprietary/bin/qmiproxy:system/bin/qmiproxy \
        vendor/samsung/d2att/proprietary/bin/qmuxd:system/bin/qmuxd \
        vendor/samsung/d2att/proprietary/bin/rmt_storage:system/bin/rmt_storage 
